// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx9VgB7arEQEckoJWCnpqzUa95XgIYKL0',
    appId: '1:658518901335:web:2fc2bea174fa07f5215912',
    messagingSenderId: '658518901335',
    projectId: 'nmemapp',
    authDomain: 'nmemapp.firebaseapp.com',
    storageBucket: 'nmemapp.appspot.com',
    measurementId: 'G-MGECZ6JEE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF_iq6tQd-1tsLa40ejvnadqy8P9QuLIE',
    appId: '1:658518901335:android:1f658f0b0ed3f923215912',
    messagingSenderId: '658518901335',
    projectId: 'nmemapp',
    storageBucket: 'nmemapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4j7ct2Q6uJOGmfcl4BCIYKmJnjcbMx8U',
    appId: '1:658518901335:ios:9112b1783d30cf6a215912',
    messagingSenderId: '658518901335',
    projectId: 'nmemapp',
    storageBucket: 'nmemapp.appspot.com',
    iosBundleId: 'com.example.mem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4j7ct2Q6uJOGmfcl4BCIYKmJnjcbMx8U',
    appId: '1:658518901335:ios:9112b1783d30cf6a215912',
    messagingSenderId: '658518901335',
    projectId: 'nmemapp',
    storageBucket: 'nmemapp.appspot.com',
    iosBundleId: 'com.example.mem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx9VgB7arEQEckoJWCnpqzUa95XgIYKL0',
    appId: '1:658518901335:web:5c2d9bddf8d252a3215912',
    messagingSenderId: '658518901335',
    projectId: 'nmemapp',
    authDomain: 'nmemapp.firebaseapp.com',
    storageBucket: 'nmemapp.appspot.com',
    measurementId: 'G-59G5H2FVT2',
  );
}
